/**
 * Stable `report.json` contract (schema family "report-1"), independent of
 * and additive to the canonical event/finding schema in `types.ts`. This
 * is what a later mobile/desktop GUI consumes for graphs and deterministic
 * recommendations — nothing here is free-text generated by a judge; every
 * field is either copied from existing typed data or computed by a pure,
 * versioned function (`src/report/*`).
 */

import type { Finding, FindingCategory, JudgeLabel, ReviewTask, RuleResult, Severity } from "./types.ts";

export const REPORT_SCHEMA_VERSION = "1.0.0" as const;
export type ReportSchemaVersion = "1.0.0";
export const SUPPORTED_REPORT_SCHEMA_VERSIONS: readonly string[] = ["1.0.0"];

export interface ReportPerQuestionProbability {
  questionId: string;
  probability: number;
}

export interface ReportJudgeSummary {
  judgeId: string;
  judgeVersion: string;
  label: JudgeLabel;
  confidence: number;
  reasonCodes: string[];
  perQuestionProbabilities: ReportPerQuestionProbability[];
  model?: string;
  usage?: { inputTokens: number; outputTokens: number };
  latencyMs?: number;
}

export interface ReportJudgeError {
  code: string;
  message: string;
  timeout: boolean;
}

export interface ReportCase {
  caseId: string;
  category: FindingCategory;
  ruleResults: RuleResult[];
  judge?: ReportJudgeSummary;
  judgeError?: ReportJudgeError;
  finding?: Finding;
  review?: ReviewTask;
  evidenceRefs: string[];
}

export interface ReportCounts {
  bySeverity: Record<Severity, number>;
  byCategory: Record<FindingCategory, number>;
  totalCases: number;
  totalFindings: number;
  totalReviews: number;
}

export type RecommendationAction = "block_release" | "human_review_required" | "monitor" | "no_action";

export interface Recommendation {
  recommendationId: string;
  policyVersion: string;
  scope: "run" | "case";
  caseId?: string;
  action: RecommendationAction;
  severity: Severity | "none";
  reasonCodes: string[];
  evidenceRefs: string[];
}

export interface ReportIntegrity {
  algorithm: "sha256";
  /** sha256 of the canonical JSON of this report with this field's `reportSha256` blanked to "". */
  reportSha256: string;
}

export interface ReportV1 {
  reportSchemaVersion: ReportSchemaVersion;
  runId: string;
  createdAt: string;
  harnessVersion: string;
  toolVersions: Record<string, string>;
  riskScorePolicyVersion: string;
  /** Deterministic, 0..1. Higher means more risk. */
  riskScore: number;
  counts: ReportCounts;
  cases: ReportCase[];
  recommendations: Recommendation[];
  integrity: ReportIntegrity;
}
